name: Build SFML

permissions: 
  contents: read
  
on:
  push:
  pull_request: 

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name : Clone repôt
        uses: actions/checkout@v7.0.1
        
      - name : Installation de conan
        uses: conan-io/setup-conan@ed3942a6883243f4af84e13e49c972f9440fa1c2
      
      - name : Installation MinGW
        uses : egor-tensin/setup-mingw@41b837e47d7f85214629d255b9c4bc3fcbe9fd63
      
      - name : Installation cmake
        run : |
          curl -L -o cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v4.3.5/cmake-4.3.5-linux-x86_64.tar.gz
          tar -xzf cmake.tar.gz
          echo "$PWD/cmake-4.3.5-linux-x86_64/bin" >> "$GITHUB_PATH"
      
      - name : Check CMAKE
        run : |
          cmake --version
          
      - name : Lancement du setup
        run : |
          chmod +x setup.sh
          ./setup.sh
        